language: rust
required: sudo
services:
- docker
matrix:
  allow_failures:
  - rust: nightly
  include:
  - rust: beta
  - rust: nightly
    env:
    - FEATURES='unstable'
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- rustup component add rustfmt-preview
script:
- cargo fmt -- --write-mode=diff
- cargo build --verbose --features "$FEATURES"
- cargo test --verbose --features "$FEATURES"
- make itest
after_success: |
  make cov
  bash <(curl -s https://codecov.io/bash) -s target/cov
