language: rust
rust:
  - stable
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || rustup component add rustfmt-preview --toolchain=nightly
script:
- cargo +nightly fmt -- --write-mode=diff
- cargo build
- cargo test
