[package]
name = "loom"
version = "0.0.1"
authors = [
    "Anatoly Yakovenko <aeyakovenko@gmail.com>"
]
license = "MIT"
documentation = "tbd"
keywords = ["blockchain"]
readme = "README.md"

[[bin]]
name = "spool"
path = "src/bin/spool.rs"

[[bin]]
name = "loom"
path = "src/bin/loom.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
getopts = "0.2"
sha2 = "0.7"

[dependencies.ed25519-dalek]
version = "^0.6"
