[package]
name = "loom"
version = "0.0.1"
authors = [
    "Anatoly Yakovenko <aeyakovenko@gmail.com>"
]
license = "MIT"
documentation = "tbd"
keywords = ["blockchain"]
readme = "README.md"

[[bin]]
name = "spool"
path = "src/bin/spool.rs"
